#! /usr/bin/sh

dest="release_builds"
platform=$1
arch=$2

function usage() {
        echo "This build script takes arguments platform and architecture and packages the program

    \$1 = Platform (win32 linux darwin\"mac\"
    \$2 = Architecture (x64 ia32)"
}

if [[ -z $platform ]] || [[ -z $arch ]]; then
        usage
        exit 1
fi

packageCommand="./node_modules/electron-packager/cli.js . HHH-Scheduler --overwrite --asar --platform=$platform --arch=$arch  --prune=true --out=$dest --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName='HHH Scheduler'"

if [[ $platform == "darwin" ]]; then
  $packageCommand --icon=./client/images/icon.icns
else
  $packageCommand --icon=./client/images/icon.ico
fi

packageName=HHH-Scheduler-$1-$2

if [[ $platform != "win32" ]]; then
  mv $dest/$packageName $dest/HHH-Scheduler-$1-x86_${2/x/}
  packageName=HHH-Scheduler-$1-x86_${2/x/}
fi

cd $dest
zip -rq $packageName.zip $packageName
cd ..
rm -rf $dest/$packageName/
