#! /usr/bin/sh

dest="release-builds"

electron-packager . HHH-Scheduler --overwrite --asar=true --platform=$1 --arch=$2 --icon=./client/images/icon.ico --prune=true --out=$dest --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="HHH Scheduler"

packageName=HHH-Scheduler-$1-$2

zip -r $dest/$packageName.zip $dest/$packageName/

rm -rf $dest/$packageName/
